#!/usr/bin/env bash
#  this script contains a funtion that checks for the ip address as well as
#  the type of the record for a given domain and sub domain

helper()
{
	#  get the type and ip_address from the dig and awk command
	#  where $3 is the type_record and $4 is the ip_address
	#  where $2 is the subdomain and $1 is the domain
	read -r "$3" "$4" <<< "$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4, $5}')"
}

subdomain_array=('www' 'lb-01' 'web-01' 'web-02')

if [ -z "$2" ]; then
	for subdomain in "${subdomain_array[@]}"; do
		helper "$1" "$subdomain" type_record ip_address
		echo "The subdomain $subdomain is a $type_record record and points to $ip_address"
	done
else
	helper "$1" "$2" type_record ip_address
	echo "The subdomain $2 is a $type_record record and points to $ip_address"
fi
