#!/usr/bin/env bash
# script that sends a file passed as an argument to a given server

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
#elif [ "$#" -eq 3 ]; then
#	scp -B "$1" "$3"@"$2":~/
elif [ "$#" -ge 4 ]; then
	yes | scp -B -i "$4" "$1" "$3"@"$2":~/
fi
