#!/usr/bin/env bash
# this script configures a server by adding a custom header to the server
path_to_nginx='/etc/nginx/sites-available/default'
is_header=`grep 'add_header X-Served-By' "$path_to_nginx"`

apt-get -y update && apt-get -y install nginx
sed -i.bak 's/listen [0-9]\{1,\}/listen 80/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:[0-9]\{1,\}/ listen \[::\]:80/g' /etc/nginx/sites-available/default
sed -i 's/^[^\(#.*\)]location \/ {/\tlocation = \/ {\n\t\treturn 200 "Hello World!\\n";/g' /etc/nginx/sites-available/default

# sed -i.bak 's/127\.0\.0\.1 *localhost/127\.0\.0\.1 localhost 03-web-01/g' '/etc/hosts'
# hostnamectl set-hostname 03-web-01

if [ -n "$is_header" ]; then
	echo "header X-Served-By already exists"
else
	sed -i.bak "s/^[^#]* *server *{/server {\n\tadd_header X-Served-By $(hostname);/g" "$path_to_nginx"
fi

service nginx restart
