#!/usr/bin/env bash
# this script configures a server by adding a custom header to the server
path_to_nginx='/etc/nginx/sites-available/default'
is_header=`grep 'add_header X-Served-By' "$path_to_nginx"`

if [ -n "$is_header" ]; then
	echo "header X-Served-By already exists"
else
	sed -i.bak "s/^[^#]* *server *{/server {\n\tadd_header X-Served-By $(hostname);/g" "$path_to_nginx"
fi

service nginx restart
