#!/usr/bin/env bash
# configures the haproxy server

# Replacement variables for haproxy configuration
path_init='/etc/default/haproxy'
path_conf='/etc/haproxy/haproxy.cfg'
web_01_ip='3.84.255.85'
web_02_ip='100.25.171.58'
frontend_string="frontend web_front\n\tbind *:80\n\tmode http\n\tdefault_backend web_backend"
backend_string="backend web_backend\n\tbalance roundrobin\n\tmode http\n\tserver web_01 $web_01_ip\n\tserver web_02 $web_02_ip"

apt-get -y update && apt-get -y upgrade
apt-get -y install haproxy

echo -e "\n$frontend_string" >> "$path_conf"
echo -e "\n$backend_string" >> "$path_conf"

check=`grep 'ENABLED' "$path_init"`
if [ -n "$check" ]; then
	sed -i.bak 's/.*ENABLED=[0-9]\{0,\}/ENABLED=1/g' "$path_init"
else
	echo "ENABLED=1" >> "$path_init"
