#!/usr/bin/env bash
# script that configures the server to redirect

apt-get -y update && apt-get -y install nginx
sed -i 's/^[^#]*server {/server {\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}/g' /etc/nginx/sites-available/default

service nginx restart
