#!/usr/bin/env bash
#pings the ip address passed as an argument to the script

script=$(echo "$0" | cut -d '/' -f2)
if [ "$#" -ne 1 ]; then
	echo "Usage: $script {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
