#!/usr/bin/env bash
# the first web server debugging script

apt -y update && apt -y install curl
apt -y install nginx
service nginx start
sed -i.bak 's/^[^#]*location \/ {/\tlocation = \/ {\n\t\treturn 200 "Hello Holberton\\n";/g' /etc/nginx/sites-available/default
service nginx restart
