#!/usr/bin/env bash
# script that creates a ssh key pair and saves it as school in current directory
if [ -f "./school" ]; then
	echo -e "./school\ny\nbetty\nbetty\n" | ssh-keygen -b 4096
else
	echo -e "./school\nbetty\nbetty\n" | ssh-keygen -b 4096
fi
