#!/usr/bin/env bash
# script that creates a ssh key pair and saves it as school in current directory
if [ -f "./school" ]; then
	echo -e "./school\ny\n" | ssh-keygen -b 4096 -P "" -N "betty"
else
	echo -e "./school\n" | ssh-keygen -b 4096 -P "" -N "betty"
fi
