#!/usr/bin/env bash
# script that creates a ssh key pair and saves it as school in current directory
if [ -f "./school" ]; then
	echo -e "y\n" | ssh-keygen -b 4096 -f "./school" -P "" -N "betty"
else
	ssh-keygen -b 4096 -f "./school" -P "" -N "betty"
fi
